### ISSUE TITLE
Add option to disable loading of content from @context

### ISSUE THREAD

**Issue by mhgrove** [jsonld-java/jsonld-java#159]
> Parsing JSON-LD will normally follow any external @context declarations.

That seems to leave the user open for someone including a malicious value for @context to tie up resources on whatever is processing the JSON-LD.

**Comment by ansell** [comment]
In general, it is not possible to process JSON-LD without the context being present. However, given that the issue won't go away just because the spec relies on it, I will setup a Java System Property to disable remote context fetching and attempt to fail quickly on these documents.

You can already do what you want with a bit of hackery, by overriding the DocumentLoader using JsonLdOptions.setDocumentLoader and set it up to either not load any remote documents or check the hosts and only load from whitelisted hosts. I don't think there is high level support for DocumentLoader in Sesame/Jena right now though, so it may require some patches to those libraries to avoid directly interacting with JSONLD-Java yourselves. 

You would then need to have whitelisted/common contexts cached and available on the classpath using the jarcache.json file [1].

[1] https://github.com/jsonld-java/jsonld-java#loading-contexts-from-classpathjar

**Comment by pumba-lt** [comment]
Loading `@context` doesn't make sense when writing JSON-LD though (not reading)?

This creates an issue in Jena 3.0.1, where `JsonLDWriter` makes an HTTP call:
https://mail-archives.apache.org/mod_mbox/jena-users/201712.mbox/browser

**Comment by pumba-lt** [comment]
On a second thought, I guess this is a classpath issue. I have a different Apache Client version on it.

**Comment by ansell** [comment]
If you set the system property ``com.github.jsonldjava.disallowRemoteContextLoading`` to the string ``true``, you may be able to eliminate the codepaths that reference the Apache HTTP Client classes, but I haven't tested that. What that will then do if remote contexts are required and you haven't cached them on the classpath is throw a JsonLdError, which may not work for you.

If you know which contexts are relevant you may be able to store cached versions on the classpath using these instructions: https://github.com/jsonld-java/jsonld-java#loading-contexts-from-classpath

In terms of requiring the context during writing, that is just how the JSONLD-API specification works when you want to transform the input using the values in the context.
