### ISSUE TITLE
incomplete list recursion with JsonLdProcessor.frame

### ISSUE THREAD

**Issue by christopher-johnson** [jsonld-java/jsonld-java#201]
I have discovered an issue with the Java JsonLdAPI related to "incomplete" list recursion output from the framing processor.   Note: this complex variety of framing works in the [Javascript library](https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js).

For example, [this frame](https://github.com/pan-dora/jsonld-fromRDF/blob/master/fromRDF/src/main/resources/frame.json) cannot produce [this result](https://raw.githubusercontent.com/pan-dora/jsonld-fromRDF/pr/fromRDF/src/main/resources/framed.json) from [this graph](https://raw.githubusercontent.com/pan-dora/jsonld-fromRDF/pr/fromRDF/src/main/resources/test2.json) .  

I have made [some experimental changes](https://github.com/pan-dora/jsonld-fromRDF/blob/pr/core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java#L1319-L1488) to the framing method and solved the issue, (though it needs a proper review and more testing).  I can submit a PR if you can formally identify and acknowledge the issue.

I suspect that the problem may derive from multiple causes, the main one being [this](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java#L1447-L1448) and [here](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java#L1467).  In the JS Api, the method makes an [implicit "subframe"](https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js#L5015-L5016) on recursion that just contains the flags.

**Comment by ansell** [comment]
The framing algorithm is probably not going to match the latest version of the JSON-LD Framing Algorithm. Part of this is because the Framing Algorithm was not standardised along with the other APIs, so it has been free to continue to change while people are still pointing to the "/latest/" URL as the reference, and part of it is that I have changed jobs since becoming maintainer and I don't actively use JSON-LD in my current job. I don't mind maintaining the existing code (merging PRs and releasing to Maven Central), but the work of getting the code up to the JSON-LD-1.1 draft specs and continually updating the Framing Algorithm as it matures are not on my current list of tasks.

Hence, I accept any help with maintenance, particular the Framing Algorithm that has a number of longstanding bugs attached to it, so a PR would be great.

A smaller test case would also be great if you can determine how to trigger the bug using a representative sample from the large file you attached.

**Comment by christopher-johnson** [comment]
@ansell thanks for the reply.  I created a [PR](https://github.com/jsonld-java/jsonld-java/pull/203) and a test case.  I skipped custom frame test 3, as I noticed that this was being used by #198.  The test case #4 is still quite complex, but not so large.  The solution is non-invasive, though I had to remove the embedValues method.  All of the tests pass.

**Comment by eroux** [comment]
@christopher-johnson I think this issue could be closed?

**Comment by christopher-johnson** [comment]
@eroux yes, resolved by https://github.com/jsonld-java/jsonld-java/commit/46cd7f2b6ef88af31cc85bcc70c055de794bee2c
