### ISSUE TITLE
Missing Jackson and SLF4J dependencies?

### ISSUE THREAD

**Issue by rodrigodesalvobraz** [jsonld-java/jsonld-java#229]
I created a skeleton Java Maven project in Eclipse, included JSONLD-java, and ran the example code given in the JSONLD-java GitHub page, and got the error:

java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper

After updating the project with an option to forced updates of snapshots, the error would not go away.

The only thing that solved it was including jackson itself in my pom.xml dependencies, but of course that is undesirable.

I also got the messages:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

which leads me to believe SLF4J is also not being indicated as a dependency.

A couple of days ago, I had included JSONLD-java without any issue. Looking at the commits, I see there has been an update to JSONLD-java's pom.xml just a day ago changing the versions of dependencies. I wonder if this was the cause.

I am attaching the sample project FYI.
[test.zip](https://github.com/jsonld-java/jsonld-java/files/1874462/test.zip)

**Comment by ansell** [comment]
I can't replicate your issue with Jackson using your test files or in any other case. If the bug continues, you should take it up on an Eclipse maven mailing list such as:

https://accounts.eclipse.org/mailing-list/m2e-users

The SLF4J message is not a bug with JSONLD-Java. It is caused by you not including your preferred logging implementation along with its SLF4J adapter, as JSONLD-Java does not want to package a particular logging implementation with the reusable library. You could include slf4j-simple to make the slf4j message go away and get logging output:

https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.slf4j%22%20AND%20a%3A%22slf4j-simple%22

The SLF4J FAQ referenced in the message includes more information about it and you may find it helpful to browse the other SLF4J documentation:

https://www.slf4j.org/codes.html#StaticLoggerBinder
